%YAML:1.0

#common parameters
savePath: "/home/zpj/ladar_and_camera_fusion/"
bag_path: "/home/zpj/ladar_and_camera_fusion/bag/biaoding-1.bag"

scan_topic_name: "/scan"
img_topic_name: "/camera/fisheye1/image_raw"

# tag info
tag_type: 1 # 1: kalibr_tag, 2: apriltag
tag_size: 0.021 # tag size, unit meter
tag_spacing: 0.3 # tag spacing, only used in kalibr_tag. For details, please see kalibr tag description.
black_border: 2 # if you use kalibr_tag black_boarder = 2; if you use apriltag black_boarder = 1
 
#camera calibration 
model_type: KANNALA_BRANDT
camera_name: cam0
image_width: 848
image_height: 800

projection_parameters:
   mu: 380.1858372084919
   mv: 375.6248764869528
   u0: 419.3196119010977
   v0: 403.5485911638869
   k2: -0.2889705613310538
   k3: 0.06595631452952637
   k4: -0.0013091214562494784
   k5: 0.0011617023900361023

