%YAML:1.0

#common parameters
savePath: "/home/zpj/ladar_and_camera_fusion/log/"
bag_path: "/home/zpj/ladar_and_camera_fusion/bag/shiyici_2023-07-06-19-21-24.bag"

scan_topic_name: "/scan"
img_topic_name: "/usb_cam/image_raw"

# tag info
tag_type: 1 # 1: kalibr_tag, 2: apriltag
tag_size: 0.021 # tag size, unit meter
tag_spacing: 0.3 # tag spacing, only used in kalibr_tag. For details, please see kalibr tag description.
black_border: 2 # if you use kalibr_tag black_boarder = 2; if you use apriltag black_boarder = 1

#camera calibration 
model_type: PINHOLE
camera_name: camera
image_width: 640
image_height: 480

# distortion_parameters:
#    k1: 0.13731888530873454
#    k2: -0.11878029118800523
#    p1: -0.029128184506354127
#    p2: 0.0
# distortion_parameters:
#    k1: 0.33016905186210493
#    k2: -0.19270726927484047
#    p1: -0.007951872733191943
#    p2: 0.0
distortion_parameters:
   k1: 0.0
   k2: 0.0
   p1: 0.0
   p2: 0.0
projection_parameters:
   fx: 1086.063108139799
   fy: 1161.6727091378539
   cx: 304.47911557665526
   cy: 497.68867352218047

